id = mywebsiteapp
name = nangallmmv_crb
mainURL = https://crb.nangallammv.edu.lk
icon = app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
allowSubdomains = true
requireDoubleBackToExit = true
edgeToEdge = true
