id = mywebsiteapp
name = My Awesome App
mainURL = https://your-website-url.com
icon = app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
allowSubdomains = true
requireDoubleBackToExit = true
edgeToEdge = true
